<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="2" ignored="1" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="154820" started-at="2018-06-30T17:17:35Z" finished-at="2018-06-30T17:20:10Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="154820" started-at="2018-06-30T17:17:35Z" finished-at="2018-06-30T17:20:10Z">
      <class name="com.dd.crm.pom.testlayer.ContactsPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.dd.crm.pom.testlayer.ContactsPageTest@e45f292]" name="setUp" is-config="true" duration-ms="78126" started-at="2018-06-30T17:17:35Z" finished-at="2018-06-30T17:18:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="contactsLabelTest()[pri:1, instance:com.dd.crm.pom.testlayer.ContactsPageTest@e45f292]" name="contactsLabelTest" duration-ms="1874" started-at="2018-06-30T17:18:53Z" finished-at="2018-06-30T17:18:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Contacts] but found [[[ChromeDriver: chrome on XP (4f364dc0b31f5f7e94ab10de0322df7f)] -> xpath: //td[@class='datacardtitle']//*[contains(text(),'Contacts')]]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Contacts] but found [[[ChromeDriver: chrome on XP (4f364dc0b31f5f7e94ab10de0322df7f)] -> xpath: //td[@class='datacardtitle']//*[contains(text(),'Contacts')]]]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at com.dd.pom.pagelayer.ContactsPage.checkContactsLabel(ContactsPage.java:44)
at com.dd.crm.pom.testlayer.ContactsPageTest.contactsLabelTest(ContactsPageTest.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactsLabelTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.dd.crm.pom.testlayer.ContactsPageTest@e45f292]" name="tearDown" is-config="true" duration-ms="1573" started-at="2018-06-30T17:18:55Z" finished-at="2018-06-30T17:18:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.dd.crm.pom.testlayer.ContactsPageTest@e45f292]" name="setUp" is-config="true" duration-ms="71591" started-at="2018-06-30T17:18:57Z" finished-at="2018-06-30T17:20:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="ExportlabelTest()[pri:2, instance:com.dd.crm.pom.testlayer.ContactsPageTest@e45f292]" name="ExportlabelTest" duration-ms="81" started-at="2018-06-30T17:20:08Z" finished-at="2018-06-30T17:20:08Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Export] but found [[[ChromeDriver: chrome on XP (4ea171aefe2455aea2cfa17f8f3c6839)] -> xpath: //a[@title='Export']]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Export] but found [[[ChromeDriver: chrome on XP (4ea171aefe2455aea2cfa17f8f3c6839)] -> xpath: //a[@title='Export']]]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at com.dd.pom.pagelayer.ContactsPage.checkExportLink(ContactsPage.java:49)
at com.dd.crm.pom.testlayer.ContactsPageTest.ExportlabelTest(ContactsPageTest.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ExportlabelTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.dd.crm.pom.testlayer.ContactsPageTest@e45f292]" name="tearDown" is-config="true" duration-ms="1205" started-at="2018-06-30T17:20:08Z" finished-at="2018-06-30T17:20:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="SKIP" signature="contactSelecttest()[pri:3, instance:com.dd.crm.pom.testlayer.ContactsPageTest@e45f292]" name="contactSelecttest" duration-ms="0" started-at="2018-06-30T17:20:10Z" depends-on-methods="com.dd.crm.pom.testlayer.ContactsPageTest.contactsLabelTest, com.dd.crm.pom.testlayer.ContactsPageTest.ExportlabelTest" finished-at="2018-06-30T17:20:10Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method ContactsPageTest.contactSelecttest()[pri:3, instance:com.dd.crm.pom.testlayer.ContactsPageTest@e45f292] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method ContactsPageTest.contactSelecttest()[pri:3, instance:com.dd.crm.pom.testlayer.ContactsPageTest@e45f292] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactSelecttest -->
      </class> <!-- com.dd.crm.pom.testlayer.ContactsPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
